version: "3"
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_USER: "root"
      MYSQL_PASS: "root"
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  backend:
    build: ./backend
    image: "backend"
    ports:
      - 3000:80
    restart: always
  frontend:
    build: ./frontend
    image: "frontend"
    ports:
      - 8080:8080
    restart: always
